// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqwInevKgBFD9PMOpGHlZVL0QJ_fGCe_M',
    appId: '1:112775318785:web:8523b7868446e0316a9f00',
    messagingSenderId: '112775318785',
    projectId: 'aitobu-database',
    authDomain: 'aitobu-database.firebaseapp.com',
    storageBucket: 'aitobu-database.firebasestorage.app',
    measurementId: 'G-N7PDXRV8BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzdioAJ8zL9pmItdF776Z17SegHDhEAiY',
    appId: '1:112775318785:android:b3240b2987c5d3a76a9f00',
    messagingSenderId: '112775318785',
    projectId: 'aitobu-database',
    storageBucket: 'aitobu-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaqZs0KsRBmkpMO6-fUGbdoJ8Lmq0oSNg',
    appId: '1:112775318785:ios:8c692f0a681b00d46a9f00',
    messagingSenderId: '112775318785',
    projectId: 'aitobu-database',
    storageBucket: 'aitobu-database.firebasestorage.app',
    iosBundleId: 'com.example.aitobuSales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaqZs0KsRBmkpMO6-fUGbdoJ8Lmq0oSNg',
    appId: '1:112775318785:ios:bac4347e65ab69116a9f00',
    messagingSenderId: '112775318785',
    projectId: 'aitobu-database',
    storageBucket: 'aitobu-database.firebasestorage.app',
    iosBundleId: 'com.aitobu.sales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqwInevKgBFD9PMOpGHlZVL0QJ_fGCe_M',
    appId: '1:112775318785:web:59e641942ff1fc106a9f00',
    messagingSenderId: '112775318785',
    projectId: 'aitobu-database',
    authDomain: 'aitobu-database.firebaseapp.com',
    storageBucket: 'aitobu-database.firebasestorage.app',
    measurementId: 'G-W3H2ZEF0XJ',
  );
}
